"""
Django settings for catatan_keuangan project.
Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv 
from os import getenv 
import os
import dj_database_url # <-- tambah ini

load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = getenv("SECRET_KEY")
DEBUG = getenv("DEBUG", "True") == "True" # <-- INI YANG BENER

ALLOWED_HOSTS = ["*"] # <-- biar Vercel bisa masuk
# nanti kalo udah online ganti jadi ["*.vercel.app"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders', # <-- tambah ini
    'account',
    'transaction',
    'dasboard'
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Catatan Keuangan API',
    'DESCRIPTION': (
        'API untuk mencatat keuangan pribadi.<br>'
        'Fitur: registrasi & login akun (JWT), manajemen kategori, '
        'dan pencatatan transaksi pemasukan/pengeluaran.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVERS': [
        {'url': 'https://catatan-keuangan-eight-khaki.vercel.app', 'description': 'Production'},
        {'url': 'http://127.0.0.1:8000', 'description': 'Local'},
    ],
    'TAGS': [
        {
            'name': 'auth',
            'description': 'Registrasi, login (JWT), dan logout akun.',
        },
        {
            'name': 'transaction',
            'description': 'CRUD transaksi (pemasukan/pengeluaran) dan kategori.',
        },
    ],
    'CONTACT': {
        'name': 'Catatan Keuangan',
    },
    'LICENSE': {
        'name': 'Proprietary',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <-- tambah ini biar static gak 404
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # <-- tambah ini
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True # <-- biar frontend bisa akses
CSRF_TRUSTED_ORIGINS = [
    "https://catatan-keuangan-eight-khaki.vercel.app",
    "https://*.vercel.app"
]

ROOT_URLCONF = 'catatan_keuangan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'catatan_keuangan.wsgi.application'

# --- DATABASE INI YANG GUA BENERIN ---
# Kalo ada DATABASE_URL (di Vercel/Supabase) pake itu, kalo gak ada pake yang lokal
if getenv("DATABASE_URL"):
    DATABASES = {
        'default': dj_database_url.parse(getenv("DATABASE_URL"))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': getenv("DB_NAME"),
            'USER': getenv("DB_USER"), # <-- lu lupa USER
            'PASSWORD': getenv("DB_PW"),
            'HOST': getenv("DB_HOST"),
            'PORT': getenv("DB_PORT"),
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jakarta' # gua ganti ke WIB biar enak
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # <-- wajib buat Vercel

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # <-- lu salah ketik MAILERS
SECURE_SSL_REDIRECT = False